name: Acquire activation file
on: [push]
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
      # You may pin to the exact commit or the version.
      # uses: game-ci/unity-activate@cda570d7590fe63b7f718e6a052e170462c07361
        uses: game-ci/unity-activate@v1.3
        with:
          # Version of unity to use for building the project.
          unityVersion: 2020.2.2f1
