name: Get activation file
on: [push]
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
     - name: Unity - Request Activation File
       uses: game-ci/unity-request-activation-file@v2.0-alpha-1
       with:
         unityVersion: 2020.2.2f1
